# Generated by Django 6.0.6 on 2026-07-25 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('tracking', '0002_bus_last_stop_reached_bus_last_stop_reached_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.CharField(blank=True, choices=[('good', 'Good'), ('moderate', 'Moderate'), ('bad', 'Bad')], default='', max_length=10)),
                ('crowding', models.CharField(blank=True, choices=[('good', 'Good'), ('moderate', 'Moderate'), ('bad', 'Bad')], default='', max_length=10)),
                ('driving', models.CharField(blank=True, choices=[('good', 'Good'), ('moderate', 'Moderate'), ('bad', 'Bad')], default='', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reports', to='tracking.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bus', 'created_at'], name='community_b_bus_id_7c04a9_idx')],
            },
        ),
    ]
