# Generated by Django 6.0.7 on 2026-07-22 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_routestop_scheduled_leg_minutes'),
        ('tracking', '0002_bus_last_stop_reached_bus_last_stop_reached_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_minutes', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_alerts', to='tracking.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_alerts', to='routes.stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_minutes', models.FloatField()),
                ('actual_minutes', models.FloatField()),
                ('delay_minutes', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_logs', to='tracking.bus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_logs', to='routes.route')),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_logs', to='routes.routestop')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['route', 'recorded_at'], name='analytics_d_route_i_a8b75f_idx'), models.Index(fields=['bus', 'recorded_at'], name='analytics_d_bus_id_29b47c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ridership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridership_events', to='tracking.bus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ridership_events', to='routes.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridership_taps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['route', 'created_at'], name='analytics_r_route_i_20a005_idx'), models.Index(fields=['bus', 'created_at'], name='analytics_r_bus_id_d5b057_idx')],
            },
        ),
    ]
