# Generated by Django 6.0.7 on 2026-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etaalert',
            name='delay_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
