# Generated by Django 6.0.7 on 2026-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='scheduled_leg_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
