# Generated by Django 6.0.6 on 2026-07-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routestop_scheduled_leg_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
