# Generated by Django 6.0.7 on 2026-07-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routestop_scheduled_leg_minutes'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_stop_reached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routes.stop'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_stop_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
